### ISSUE TITLE
Conn_id dinamic

### ISSUE THREAD

**Issue by pauloricardoferreira** [damavis/airflow-hop-plugin#28]
hello. I have a suggestion for improvement. in the conn_id, it could be passed as a parameter in the DAG, if not informed, use the default. I have seen this need in clients with different servers. thanks

**Comment by PereAL7** [comment]
Hello, the conn_id can be passed as a parameter in both the pipeline and workflow operators (the parameter is called "hop_conn_id"). Is this what you meant?

**Comment by pauloricardoferreira** [comment]
Exactly.

I would like to use a name other than hop_default.

Reading the plugin code, I understood that it is fixed, not being possible to change or inform another value.

I read the Pentaho plugin and understood that it is possible.

**Comment by piffall** [comment]
Hi @pauloricardoferreira ,

It seems that you probably misunderstood the code.
https://github.com/damavis/airflow-hop-plugin/blob/ef94795d706cb2beaf234356a06d1d7dd28955c7/airflow_hop/operators.py#L61

This is the default value when not provided, but you can provide it if you want it this way:

```python
my_workflow =  HopWorkflowOperator(workflow='workflows/my_workflow.hwf',
                                   project='my_project',
                                   log_level='Basic',
                                   hop_conn_id='another_hop_connection')
```

**Comment by pauloricardoferreira** [comment]
Tks
