### ISSUE TITLE
Error Operator - HopWorkflowOperator

### ISSUE THREAD

**Issue by mathsteen** [damavis/airflow-hop-plugin#30]
Hello,
Good afternoon,

I'm trying to run a Hop workflow with Airflow using your plugin.

I'm getting the following error:

File "/usr/local/lib/python3.10/dist-packages/airflow_hop/[hooks.py](https://hooks.py/)", line 177, in register_workflow
    raise AirflowException('{}: {}'.format(
airflow.exceptions.AirflowException: ERROR: org.apache.hop.core.exception.HopXmlException:
Error reading information from XML string:
<workflow_configuration><workflow>

Caused by: org.xml.sax.SAXParseException; lineNumber: 476; columnNumber: 5394; The element type "workflow_configuration" must be terminated by the matching end-tag "</workflow_configuration>

I have a simple workflow where it checks some databases in parallel and sends an email if everything is ok.

I use environment variables for banks and email.

Thanks in advance!

Hop version 2.7
Airflow version 2.8

[dag_id=hop_teste_run_id=scheduled__2024-01-10T18_40_00+00_00_task_id=hop_teste_attempt=1.log](https://github.com/damavis/airflow-hop-plugin/files/13893858/dag_id.hop_teste_run_id.scheduled__2024-01-10T18_40_00%2B00_00_task_id.hop_teste_attempt.1.log)

Dag Example:

from airflow import DAG
from datetime import datetime
from airflow_hop.operators import HopWorkflowOperator

with DAG(
dag_id='hop_teste',
schedule="*/5 * * * *",
start_date=datetime(2023, 1, 1),
catchup=False,
tags=['docker', 'hop', 'airflow']
) as dag:
TASK = HopWorkflowOperator(
task_id='hop_teste',
hop_conn_id='hop_server_container',
workflow='teste.hwf',
project_name='dlk',
log_level='Basic')

**Comment by mathsteen** [comment]
Dag Example:

from airflow import DAG
from datetime import datetime
from airflow_hop.operators import HopWorkflowOperator

with DAG(
    dag_id='hop_teste', 
    schedule="*/5 * * * *", 
    start_date=datetime(2023, 1, 1), 
    catchup=False,
    tags=['docker', 'hop', 'airflow']
    ) as dag:
    TASK = HopWorkflowOperator(
        task_id='hop_teste',
        hop_conn_id='hop_server_container',
        workflow='teste.hwf',
        project_name='dlk',
        log_level='Basic')

**Comment by PereAL7** [comment]
Hi,
I think this error could be due to a faulty configuration file. Can you check if the file is correct?

**Comment by mathsteen** [comment]
Hello 
Did you see the log I sent as an attachment? 
And where would this error be?

**Comment by PereAL7** [comment]
Hi, 
After taking another look to your problem I think it probably is failing due to the xml produced in the XmlBuilder and not a faulty config file. 
It looks like the encoding of the resulting string may be the problem but I'm not too sure as I've not been able to reproduce the error. 
If you could share your workflow file it would be really helpful!

**Comment by mathsteen** [comment]
Yes, I will,
Locally, the problem really is when it goes to the Hop Server with Airflow.
There's my Workflow!
I'm using the latest version of Airflow and the latest version of Hop.

Hop version 2.7
Airflow version 2.8

[teste.txt](https://github.com/damavis/airflow-hop-plugin/files/13904890/teste.txt)

**Comment by PereAL7** [comment]
Greetings, 
I've released a new version that should have your problem fixed. As I expected, the encoding of the xml caused some characters to dissapear when being sent to the Hop Server.
Thank you for you cooperation!
